os:
  - linux
dist: trusty

addons:
  apt:
    packages:
      - nim

language: c

before_script:
  - set -e
  - set -x
  - nimble install jester scram -y

script:
  - nim c src/urlstrap.nim

notifications:
  email: true